$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: voice-classification-train-environment
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: conda.yaml
description: Environment created for training